# Generated by Django 5.0.7 on 2024-07-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=10, null=True)),
                ('hourATD', models.IntegerField(null=True)),
                ('minuteATD', models.IntegerField(null=True)),
                ('hourATA', models.IntegerField(null=True)),
                ('minuteATA', models.IntegerField(null=True)),
                ('original_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky.flight')),
            ],
        ),
    ]
